# Generated by Django 2.1.2 on 2018-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='talk_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('friendID', models.IntegerField()),
                ('talkInfo', models.TextField()),
                ('msgType', models.IntegerField(default=1)),
                ('createTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=32)),
                ('userName', models.CharField(max_length=32)),
                ('saying', models.CharField(max_length=52)),
                ('info', models.CharField(default=None, max_length=2048)),
                ('friendsID', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='publish',
        ),
    ]
