# Generated by Django 2.1.2 on 2018-12-14 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20181203_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 18, 37, 58, 856915)),
        ),
    ]
