# Generated by Django 2.1.3 on 2018-12-22 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20181216_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 23, 40, 59, 70576)),
        ),
    ]
