# Generated by Django 2.1.3 on 2018-12-23 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20181222_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 21, 20, 34, 524519)),
        ),
    ]
